diff --git a/Makefile b/Makefile
new file mode 100644
index 0000000..0f13965
--- /dev/null
+++ b/Makefile
@@ -0,0 +1,44 @@
+# gcc -O2 -shared -fPIC -I "$LUA_HEADERS" pb.c -o pb.so
+
+T=pb
+
+# Default installation prefix
+PREFIX=/usr/local
+
+LUA_VERSION = 5.1
+
+# System's libraries directory (where binary libraries are installed)
+LUA_LIBDIR= $(PREFIX)/lib/lua/$(LUA_VERSION)
+
+# Lua includes directory
+LUA_INC += -I$(PREFIX)/include
+LUA_INC += -I/usr/include/lua$(LUA_VERSION) -I/usr/include/lua/$(LUA_VERSION)
+
+LIB_OPTION= -shared #for Linux
+
+# Compilation directives
+WARN= -Wall -fPIC -W -Waggregate-return -Wcast-align -Wmissing-prototypes -Wnested-externs -Wshadow -Wwrite-strings
+INCS= $(LUA_INC)
+CC= gcc
+
+SRCS= $T.c
+OBJS= $T.o
+
+lib: pb.so
+
+.c.o:
+	$(CC) $(WARN) $(INCS) $(CFLAGS) -c -o $@ $<
+
+pb.so: $(OBJS)
+	$(CC) $(CFLAGS) $(LDFLAGS) $(LIB_OPTION) -o pb.so $(OBJS)
+
+# test: lib
+#         LUA_CPATH=./src/?.so lua tests/test.lua
+
+install:
+	mkdir -p $(DESTDIR)$(LUA_LIBDIR)
+	cp $(T).so $(DESTDIR)$(LUA_LIBDIR)
+	cp protoc.lua $(DESTDIR)$(LUA_LIBDIR)
+
+clean:
+	rm -f pb.so $(OBJS)
