name: Build packages

on:
  pull_request:
    branches:
      - main
    paths:
      - 'main/**'
      - 'user/**'

concurrency:
  group: ${{ forgejo.workflow }}-${{ forgejo.ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: 1
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 1

jobs:
  build:
    name: Build packages

    strategy:
        matrix:
            runner: [casuarina-x86]
            # runner: [casuarina-x86, casuarina-arm]
        fail-fast: false

    runs-on: ${{ matrix.runner }}
    container:
      image: wezm/casuarina-ci:20260319-1
    if: "!contains(forgejo.event.pull_request.title, '[ci skip]') && !contains(forgejo.event.pull_request.body, '[ci skip]')"

    env:
      update_check: |-
        ${{
          ( !contains(forgejo.event.pull_request.title, '[update skip]')
          && !contains(forgejo.event.pull_request.body, '[update skip]') )
          && '--update-check'
          || ''
        }}

    steps:
      - name: Checkout
        uses: classabbyamp/treeless-checkout-action@v1

      - name: Restore cbuild cache
        id: cache-cbuild
        uses: actions/cache/restore@v4
        with:
          path: |
            ./cbuild_cache
            ./sources
          key: ${{ runner.os }}-${{ runner.arch }}-cbuild-ci-cache-${{ forgejo.run_id }}
          # checks prefix of cache stored below and grabs the one from the latest run_id that is
          # always saved. we do this because things like source fetch / dependencies don't care
          # about success.
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-cbuild-ci-cache

      - name: Set up cbuild configuration
        run: sh .ci/setup-cbuild.sh

      - name: Build and test packages
        run: python3 cbuild -W ${{ env.update_check }} -t bulk-pkg 'git:main..+!\[ci skip\]'

      - name: Save cbuild cache
        uses: actions/cache/save@v4
        if: ${{ !cancelled() }}
        with:
          path: |
            ./cbuild_cache
            ./sources
          key: ${{ runner.os }}-${{ runner.arch }}-cbuild-ci-cache-${{ forgejo.run_id }}
