pkgname = "gn"
pkgver = "2.5.8"
pkgrel = 0
#build_style = "gnu_configure"
_commit = "1de45d1a11cc9f8cb5c75a031386151e1c384847"
#  make_cmd = "gmake"
#  make_dir = "."
#  make_install_args = ["install-doc-man"]
hostmakedepends = ["ninja", "python", "git"]
#  makedepends = ["ncurses-devel"]
depends = ["ninja"]
pkgdesc = "Meta-build system that generates build files for Ninja"
maintainer = "Wesley Moore <wes@wezm.net>"
license = "BSD-3-Clause"
url = "https://gn.googlesource.com/gn"
source = f"https://dev.alpinelinux.org/archive/gn/gn-{_commit}.tar.xz"
# tarballs generated by googlesource.com are not stable
sha256 = "c0b1aa6866eb2e90ac3326fa92331f9182f93057a5a4d94a96d82904f231c2a6"
# test suite tries to access /dev/tty which fails
options = ["!check"]

# We could do_fetch but there would be no way to do checksums...

def do_build(self):
    self.do("python", "build/gen.py", "--no-static-libstdc++", "--no-strip")
    self.do("ninja", "-C", "out")

def do_check(self):
    self.do("out/gn_unittests")

def do_install(self):
    self.install_bin("out/gn")

def post_install(self):
    self.install_license("LICENSE")
