diff --git a/Makefile b/Makefile
index 79e12a9..c0c8f50 100644
--- a/Makefile
+++ b/Makefile
@@ -21,9 +21,9 @@ CC = gcc
 LD = gcc
 RM = rm -f
 
-CPPFLAGS = -I $(PNGINC)
+CPPFLAGS =
 
-CFLAGS = -g -O3 -fomit-frame-pointer -Wall
+CFLAGS = $(shell pkgconf --cflags libpng zlib)
 # [note that -Wall is a gcc-specific compilation flag ("all warnings on")]
 LDFLAGS =
 O = .o
@@ -31,7 +31,7 @@ E =
 
 PNGCRUSH  = pngcrush
 
-LIBS = -L$(PNGLIB) -L$(ZLIB) -lpng -lz -lm
+LIBS = $(shell pkgconf --libs libpng zlib) -lm
 
 OBJS  = pngcrush$(O)
 
@@ -54,7 +54,7 @@ pngcrush$(O): pngcrush.c cexcept.h
 	mv png.h_embedded png.h
 
 $(PNGCRUSH)$(E): $(OBJS)
-	$(LD) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)
+	$(CC) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)
 
 # maintenance ---------------------------------------------------------------
 
